---

- name: ip_rules | Fetch private IP match rule
  iplookup:
    ips: "{{ ansible_all_ipv4_addresses }}"
    rules : "{{ openswan_private_address_rule }}"
  connection: local
  sudo: False
  register: private_ip
  when: openswan_private_address is not defined or openswan_private_address == ''

- name: ip_rules | Set private IP match rule
  set_fact:
    openswan_private_address="{{ private_ip.matched_ip }}"
  when: openswan_private_address is not defined or openswan_private_address == ""

- name: ip_rules | Fetch public IP match rule
  iplookup:
    ips: "{{ ansible_all_ipv4_addresses}}"
    rules : "{{ openswan_public_address_rule }}"
  connection: local
  register: public_ip
  sudo: False
  when: openswan_public_address is not defined or openswan_public_address == ''

- name: ip_rules | Set public_ip IP match rule
  set_fact:
    openswan_public_address="{{ public_ip.matched_ip }}"
  when: openswan_public_address is not defined or openswan_public_address == ""