---

- name: pp_conf | set /etc/pam.d/ppp
  template:
    src=pam-ppp.j2
    dest=/etc/pam.d/ppp
    owner=root

- name: ppp_config | Create/var/log/ppp-ipupdown.log
  command: touch touch /var/log/ppp-ipupdown.log
  changed_when: False

- name: ppp_config | Deploy xl2tpd config file
  template:
    src=xl2tpd.conf.j2
    dest=/etc/xl2tpd/xl2tpd.conf
    owner=root
  notify: restart xl2tpd

- name: ppp_config | Deploy xl2tpd  options.xl2tpd file
  template:
    src=options.xl2tpd.j2
    dest=/etc/ppp/options.xl2tpd
    owner=root
  notify: restart xl2tpd