---

- name: user_secrets | set /etc/ppp/pap-secrets
  template:
    src=pap-secrets.j2
    dest=/etc/ppp/pap-secrets
    owner=root
  notify: restart openswan

- name: user_secrets | Set users
  template:
    src=pap-secrets.j2
    dest=/etc/ppp/pap-secrets
    owner=root
  notify:
     - restart openswan
     - restart xl2tpd

- name: user_secrets | Set chap-secrets
  template:
    src=chap-secrets.j2
    dest=/etc/ppp/chap-secrets
    owner=root
  notify:
     - restart openswan
     - restart xl2tpd